name: CMake CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg install zeromq:x64-windows boost-lockfree:x64-windows spdlog:x64-windows gtest:x64-windows

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_STANDARD=23

    - name: Build
      run: |
        cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: build
      run: |
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure