jobs:
  build:
    runs-on: windows-latest
    steps:
      # Other steps like checkout and setup remain unchanged
      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg install zeromq:x64-mingw-dynamic --recurse --debug || exit 1
        shell: cmd

      - name: Check vcpkg installed libraries
        run: |
          dir vcpkg\installed\x64-mingw-dynamic\lib
          dir vcpkg\installed\x64-mingw-dynamic\include
        shell: cmd

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-mingw-dynamic -G "MinGW Makefiles" -DCMAKE_CXX_STANDARD=23
        shell: cmd

      # Build step remains unchanged
      - name: Build
        run: cmake --build build
        shell: cmd